spring:
  application:
    name: urlshortener
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid,profile,email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
    jwt:
      secret: ${JWT_SECRET}
      expiration: 360000000

  datasource:
    url: jdbc:mysql://localhost:3306/urlShort
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
url:
  expiration:
    minutes: 5
logging:
  level:
    org:
      springframework:
        security: DEBUG
