spring:
  application:
    name: urlshortener
  security:
    jwt:
      secret: TXlTZWNyZXRLZXlNeVNlY3JldEtleQ==
      expiration: 360000000

  datasource:
    url: jdbc:mysql://localhost:3306/urlShort
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kraft-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

url:
  expiration:
    minutes: 5
  origin: http://localhost:8080
  endpoint: /r/
logging:
  level:
    org:
      springframework:
        security: DEBUG